workflows:
    dynamic-configuration-example:
        name: Dynamic Configuration App
        triggering: &triggering
          events:
            - push
            - pull_request
        scripts:
            - ./examples/dynamic-configuration-example/gradlew -p examples/dynamic-configuration-example assembleDebug
        artifacts:
            - app/build/outputs/**/*.apk
    optimization-example:
        name: Optimization App
        triggering: *triggering
        scripts:
            - ./examples/dynamic-configuration-example/gradlew -p examples/identity-transfer-example assembleDebug
        artifacts:
            - app/build/outputs/**/*.apk
    identity-transfer-example:
        name: Identity Transfer App
        triggering: *triggering
        scripts:
            - ./examples/dynamic-configuration-example/gradlew -p examples/optimizing-programmatically-using-json-example assembleDebug
        artifacts:
            - app/build/outputs/**/*.apk
