workflows:
    dynamic-configuration-example:
        name: Dynamic Configuration App
        triggering: &triggering
          events:
            - push
            - pull_request
          branch_patterns:
            - pattern: '*'
              include: true
              source: true
        scripts:
            - ./examples/dynamic-configuration-example/gradlew -p examples/dynamic-configuration-example assembleDebug
        publishing:
            email:
                recipients:
                    - e1ef44bb.thunderhead.com@emea.teams.ms
        artifacts:
            - app/build/outputs/**/*.apk
    optimization-example:
        name: Optimization App
        triggering: *triggering
        scripts:
            - ./examples/dynamic-configuration-example/gradlew -p examples/identity-transfer-example assembleDebug
        publishing:
            email:
                recipients:
                    - e1ef44bb.thunderhead.com@emea.teams.ms
        artifacts:
            - app/build/outputs/**/*.apk
    identity-transfer-example:
        name: Identity Transfer App
        triggering: *triggering
        scripts:
            - ./examples/dynamic-configuration-example/gradlew -p examples/optimizing-programmatically-using-json-example assembleDebug
        publishing:
            email:
                recipients:
                    - e1ef44bb.thunderhead.com@emea.teams.ms
        artifacts:
            - app/build/outputs/**/*.apk