name: Tag and Release on PR Merge
on:
  pull_request:
    types: [closed]
#     branches: 
#       - 'release/*'
jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get Release Branch Name
        id: get_release_branch_name
        run: echo "::set-output name=branch_name::${{ github.head_ref }}"

      - name: Echo Release Branch Name
        id: echo_release_branch_name
        run: echo '${{ steps.get_release_branch_name.outputs.branch_name }}'
      
      - name: Get Merge sha
        id: get_merge_sha
        run: echo "::set-output name=merge_sha::${{ github.sha }}"
      
      - name: Echo Merge sha
        id: echo_merge_sha
        run: echo '${{ steps.get_merge_sha.outputs.merge_sha }}' 
        
      - name: Create Tag Variable
        id: create_tag_variable
#         if: contains(steps.get_release_branch_name.outputs.branch_name, 'release/')
        run: |
          BRANCH=${{ steps.get_release_branch_name.outputs.branch_name }}
          TAG="$(sed 's/release\///g' <<< $BRANCH)"
          echo ::set-output name=tag::"$TAG"
        
      - name: Echo Tag Name
        id: echo_tag_name
        run: echo "${{ steps.create_tag_variable.outputs.tag }}"
      
#       - name: Tag Release Merge
#         id: tag_release_merge
#         uses: tvdias/github-tagger@v0.0.1
#         with:
#           repo-token: "${{ secrets.GITHUB_TOKEN }}"
#           tag: "${{ steps.create_tag_variable.outputs.tag }}"
#           commit-sha: "${{ steps.get_merge_sha.outputs.merge_sha }}"
